### ISSUE TITLE
support magnet?

### ISSUE THREAD

**Issue by diegargon** [irazasyed/php-transmission-sdk#8]
I using the method addUrl to add torrents, seems work fine except for magnets, i don't known if i doing something wrong or the libs not support magnets

`Fatal error: Uncaught Transmission\Exception\TransmissionException: gotMetadataFromURL: http error 404: Not Found in /var/www/[EDITED]/trackerm/vendor/irazasyed/php-transmission-sdk/src/HttpClient/Plugin/ExceptionThrower.php:29 Stack trace: #0 /var/www/[EDITED]/trackerm/vendor/php-http/httplug/src/Promise/HttpFulfilledPromise.php(31): Transmission\HttpClient\Plugin\ExceptionThrower->Transmission\HttpClient\Plugin\{closure}() #1 /var/www/[EDITED]/trackerm/vendor/irazasyed/php-transmission-sdk/src/HttpClient/Plugin/ExceptionThrower.php(48): Http\Client\Promise\HttpFulfilledPromise->then() #2 /var/www/[EDITED]/trackerm/vendor/php-http/client-common/src/PluginChain.php(48): Transmission\HttpClient\Plugin\ExceptionThrower->handleRequest() #3 /var/www/[EDITED/trackerm/vendor/php-http/client-common/src/PluginChain.php(63): Http\Client\Common\PluginChain->Http\Client\Common\{closure}() #4 /var/www/[EDITED]/trackerm/vendor/php-http/client-common/src/PluginClient.php(90): Http\Client\Common\PluginChain->__invoke() #5 / in /var/www/[EDITED]/trackerm/vendor/irazasyed/php-transmission-sdk/src/HttpClient/Plugin/ExceptionThrower.php on line 29`

**Comment by diegargon** [comment]
forget it, is not API problem.
